export const REDUX_STATE = {
	auth: 'auth',
	application: 'application',
	archivedStories: 'archivedStories',
	categories: 'categories',
	comments: 'comments',
	draftStories: 'draftStories',
	followers: 'followers',
	following: 'following',
	guildatars: 'guildatars',
	likes: 'likes',
	languages: 'languages',
	notifications: 'notifications',
	marketplace: 'marketplace',
	stories: 'stories',
	savedBy: 'savedBy',
	storyPages: 'storyPages',
	savedStories: 'savedStories',
	userActivity: 'userActivity',
	userItems: 'userItems',
	userStories: 'userStories',
	users: 'users',
	views: 'views',
	toast: 'toast',
};
